[package]
name = "ardent-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
ardent-core = { path = "../ardent-core" }
ardent-render = { path = "../ardent-render" }
winit.workspace = true
pollster = "0.4"
